use_frameworks!

platform :ios, '11.0'

target 'SNKThreadMonitor_Example' do
  pod 'SNKThreadMonitor', :path => '../'
  pod 'SwiftyJSON'
  target 'SNKThreadMonitor_Tests' do
    inherit! :search_paths

    
  end
end
